#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
image="${LIBRATBAG_BUILD_IMAGE:-libratbag-build}"
ubuntu_version="${UBUNTU_VERSION:-26.04}"
builddir="${BUILD_DIR:-builddir-docker}"
destdir="${DESTDIR:-_docker-install}"
package_dir="${PACKAGE_DIR:-dist}"
package_name="${PACKAGE_NAME:-libratbag}"
package_revision="${PACKAGE_REVISION:-1}"
prefix="${PREFIX:-/usr}"
tests="${TESTS:-false}"
documentation="${DOCUMENTATION:-false}"

case "$(uname -m)" in
    x86_64) default_libdir="lib/x86_64-linux-gnu" ;;
    aarch64|arm64) default_libdir="lib/aarch64-linux-gnu" ;;
    armv7l) default_libdir="lib/arm-linux-gnueabihf" ;;
    *) default_libdir="lib" ;;
esac
libdir="${LIBDIR:-${default_libdir}}"

docker build \
    --build-arg "UBUNTU_VERSION=${ubuntu_version}" \
    -f "${repo_root}/Dockerfile.build" \
    -t "${image}:${ubuntu_version}" \
    "${repo_root}"

docker run --rm \
    -v "${repo_root}:/src" \
    -w /src \
    "${image}:${ubuntu_version}" \
    bash -lc "
        set -euo pipefail
        for path in '${builddir}' '${destdir}' '${package_dir}'; do
            if [ -e \"\${path}\" ]; then
                chown -R '$(id -u):$(id -g)' \"\${path}\"
            fi
        done
    "

docker run --rm \
    -u "$(id -u):$(id -g)" \
    -v "${repo_root}:/src" \
    -w /src \
    "${image}:${ubuntu_version}" \
    bash -lc "
        set -euo pipefail
        rm -rf '${destdir}'
        meson setup '${builddir}' --prefix='${prefix}' --libdir='${libdir}' -Dtests='${tests}' -Ddocumentation='${documentation}' --reconfigure || \
            meson setup '${builddir}' --prefix='${prefix}' --libdir='${libdir}' -Dtests='${tests}' -Ddocumentation='${documentation}'
        meson compile -C '${builddir}'
        if [ '${tests}' = true ]; then
            meson test -C '${builddir}' --print-errorlogs
        fi
        DESTDIR=\"/src/${destdir}\" meson install -C '${builddir}'

        version=\"\$(meson introspect '${builddir}' --projectinfo | python3 -c 'import json, sys; print(json.load(sys.stdin)[\"version\"])')\"
        arch=\"\$(dpkg --print-architecture)\"
        deb_root='/src/${destdir}'
        debian_dir=\"\${deb_root}/DEBIAN\"
        deb_name='${package_name}'
        deb_version=\"\${version}-${package_revision}\"
        deb_file=\"/src/${package_dir}/\${deb_name}_\${deb_version}_\${arch}.deb\"

        rm -rf \"\${debian_dir}\"
        mkdir -p \"\${debian_dir}\" \"/src/${package_dir}\"

        installed_size=\"\$(du -sk \"\${deb_root}\" | awk '{print \$1}')\"
        cat > \"\${debian_dir}/control\" <<CONTROL
Package: \${deb_name}
Version: \${deb_version}
Section: utils
Priority: optional
Architecture: \${arch}
Maintainer: Local build <root@localhost>
Installed-Size: \${installed_size}
Depends: libc6, libevdev2, libglib2.0-0t64 | libglib2.0-0, libjson-glib-1.0-0, libsystemd0, libudev1, libunistring5 | libunistring2, python3, python3-evdev, python3-gi, systemd
Description: DBus daemon and tools for configuring gaming mice
 Local package generated by scripts/docker-build.sh.
CONTROL

        cat > \"\${debian_dir}/postinst\" <<'POSTINST'
#!/bin/sh
set -e

if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload || true
    systemctl reload dbus.service || true
    systemctl enable ratbagd.service || true
    systemctl restart ratbagd.service || true
fi

exit 0
POSTINST

        cat > \"\${debian_dir}/prerm\" <<'PRERM'
#!/bin/sh
set -e

if [ \"\$1\" = remove ] || [ \"\$1\" = deconfigure ]; then
    if command -v systemctl >/dev/null 2>&1; then
        systemctl stop ratbagd.service || true
    fi
fi

exit 0
PRERM

        cat > \"\${debian_dir}/postrm\" <<'POSTRM'
#!/bin/sh
set -e

if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload || true
    systemctl reload dbus.service || true
fi

exit 0
POSTRM

        chmod 0755 \"\${debian_dir}/postinst\" \"\${debian_dir}/prerm\" \"\${debian_dir}/postrm\"
        dpkg-deb --root-owner-group --build \"\${deb_root}\" \"\${deb_file}\"
    "

cat <<EOF

Build complete.

Staged files are in:
  ${repo_root}/${destdir}

Debian package is in:
  ${repo_root}/${package_dir}

To install them onto this machine, run:
  sudo apt install ${repo_root}/${package_dir}/${package_name}_*.deb
EOF
